APTCACHER="192.168.122.1"
CACHEPORT="3142"
NFSSERVERER="192.168.122.1"
NFSPORT="2049"
DNS="10.89.36.196"
site="https://intranet.corporativo.com"
sigh="10.0.0.30"
ENABLE_BACKUP=true
ENABLE_FLATPAK_CACHE=true
ENABLE_HEALTH_APPS=false
hostsallow0="sshd: 192.168.123.0/24"
hostsallow1="sshd: 10.0.0.0/16"
hostsallow2="sshd: 192.168.122.0/24"
hostsallow3="sshd: 127.0.0.1"
hostsdeny="sshd: ALL"



